9elements/firmware-action

docker/uefi_edk2-stable202008/Dockerfile, docker/uefi_edk2-stable202105/Dockerfile, docker/uefi_edk2-stable202111/Dockerfile, docker/uefi_edk2-stable202205/Dockerfile, docker/uefi_vUDK2017/Dockerfile
Add docker files to handle UEFI builds.
=> Uefi docker

.editorconfig, CONTRIBUTING.md
Add initial draft of contributing document along with [editorconfig](https://editorconfig.org/) specification.
=> Contributing

action/coreboot.go, action/kconfig.go, pkg/kconfig.go, pkg/kconfig_test.go
Migrate kconfig to pkg and add unit-tests.
=> Migrate kconfig to pkg

docker/coreboot/Dockerfile, docker/edk2/Dockerfile
Github actions require node inside the container to run.
Add nodejs to all Dockerfiles.
=> fix(docker): Add nodejs

action/recipes/config.go, action/recipes/config_test.go, action/recipes/coreboot.go, action/recipes/coreboot_test.go, action/recipes/edk2.go, action/recipes/edk2_test.go, action/recipes/linux.go, action/recipes/linux_test.go, action/recipes/recipes.go, tests/example_config.json
This nicely cleans up the JSON config file of unnecessary nesting.
=> refactor: switch to structs with embedded types

action/recipes/config.go, action/recipes/coreboot.go, action/recipes/edk2.go, action/recipes/edk2_test.go, action/recipes/linux.go, tests/example_config.json
=> refactor edk to make it more universal

.github/workflows/docker-build-and-test.yml, .github/workflows/documentation-pages.yml
=> ci: run docker build workflows on release

action/filesystem/filesystem.go, action/recipes/recipes.go, package-lock.json
[Megalinter was complaining](https://github.com/9elements/firmware-action/actions/runs/7885251382/job/21515959341) about some old versions, so I run update on all packages.
```
❌ Linted [REPOSITORY] files with [grype]: Found 1 error(s) - (12.34s) (expand for details)
- Using [grype v0.74.5] https://megalinter.io/7.9.0/descriptors/repository_grype
- MegaLinter key: [REPOSITORY_GRYPE]
- Rules config: [.grype.yaml]
--Error detail:
NAME       INSTALLED  FIXED-IN  TYPE  VULNERABILITY        SEVERITY 
ip         2.0.0                npm   GHSA-78xj-cgh5-2h22  High      
semver     5.7.1      5.7.2     npm   GHSA-c2qf-rxjj-qqgw  Medium    
semver     7.3.8      7.5.2     npm   GHSA-c2qf-rxjj-qqgw  Medium    
word-wrap  1.2.3      1.2.4     npm   GHSA-j8xg-fqg3-53r7  Medium
discovered …
```
=> chore: update npm packages and some unused variables

.github/dependabot.yml
=> ci(dependabot): tweak config

.commitlint.config.js, .github/workflows/lint.yml
=> fix(commitlint): add config increasing max line length

.github/workflows/documentation-pages.yml
The cache reduces time to complete from 7 minutes to less than 1
=> Fix mdbook and add cache because why not

docker/coreboot/Dockerfile, docker/edk2/Dockerfile, docker/linux/Dockerfile
- add openssh server
- add few editors, tools and utilities people would expect
- change SSH configuration to allow password on root user
These changes are needed for upcomming PR #147
=> feat(docker): prepare container for interactive debugging

docker/edk2/Dockerfile
=> add rust support into edk2

.dagger-ci/daggerci/requirements.txt
This reverts commit a3f2a7810ee15d857f2b48eec61bd6b754b28588.
=> Revert "build(deps): update pytest requirement in /.dagger-ci/daggerci"

.cspell.json, .dagger-ci/daggerci/lib/docker_compose.py, .dagger-ci/daggerci/lib/github.py, .dagger-ci/daggerci/lib/orchestrator.py, .dagger-ci/daggerci/lib/results.py
Print size of the tarball generated by dagger build.
While at it, I also ran `task format` and it seems that few things here and there are now different. It is in separate commit.
=> feature: minor improvement of python script building docker containers

action/main.go
It is nice to get a confirmation that the build was successful and without error.
=> feat(action): print a message on success

action/container/ssh.go
=> feat(action): notify user that interactivity rolls back state

action/recipes/stitching.go, action/recipes/stitching_test.go
fixes #184 
It can be handy sometimes to ignore if a blob is defined, but the actual file is missing. For example for a matrix builds where one variation needs the blob and another one does not.
=> feat(action): add option to ignore missing blob files

.github/workflows/docker-build-and-test.yml, docker/compose.yaml, docker/uroot/Dockerfile, tests/test_uroot.sh
fixes #260 
When I added the container for the first time I was seeing some validation errors. So just to make sure it is actual syntax issue in `compose.yaml` and not some python error I have also added extra validation step. It is unnecessary, but does not slow anything down, so I figured why not.
=> ci(docker): add first u-root container v0.14.0

docker/coreboot/Dockerfile, docker/edk2/Dockerfile
This dependency is missing for edk2 build which can be handled by coreboot
=> add missing dependencies into coreboot and edk2 containers

.github/workflows/docker-build-and-test.yml, .github/workflows/documentation-pages.yml, .github/workflows/example.yml, .github/workflows/go-test.yml, .github/workflows/lint.yml, .github/workflows/pytest.yml
=> ci: tweak run conditions to reduce number of CIs

.github/workflows/release.yml
=> fix(release): remove leftover javascript stuff

action.yml
The `compile` input it not a boolean but a string instead. So the `if` comparison was wrong.
Caught it with [firmware-action-example](https://github.com/9elements/firmware-action-example) when [dependabot tried to update](https://github.com/9elements/firmware-action-example/actions/runs/10171703448/job/28133149558) to latest action release.
=> fix(action): if statement using compile input

.github/CODEOWNERS
I think it would be handy, and super nice if / when more people will start working on this project.
=> docs: add CODEOWNERS file

.cspell.json, .github/labeler.yml, .github/workflows/bot--labeler.yml
- automatically label new pull requests
=> feat(ci): add labeler bot

.github/workflows/bot--labeler.yml
- rename it to fit better into the rest of workflows we have
=> chore: rename labeler workflow

.github/workflows/release-prepare.yml
- since we are using Conventional Commits, let's put them to work
- we can use the Conventional Commits to determine what the next version should be
=> feat(release): automatically determinate the next version

.cspell.json, .github/workflows/bot--reminder.yml
- this can be useful for some issues that are blocked by mainstream to periodically ping on issues
- perfect for issue #302
=> feat(ci): add reminder bot

.github/workflows/bot--reminder.yml
- schedule trigger is not supported
- fix typo
=> fix(ci): reminder bot

.github/workflows/pytest.yml
=> feat(ci): use arduino/setup-task to get taskfile

.github/workflows/pytest.yml
Switch from hard-coded version of docker-compose to latest one
fixes #309
=> fix(docker): download latest version of docker-compose

.github/workflows/docker-build-and-test.yml, .github/workflows/example.yml, tests/example_config__edk2.json, tests/test_edk2.sh
=> fix(edk2): GCC5 was depreciated in edk2-stable202305

docker/compose.yaml, docker/coreboot/Dockerfile
- they are not needed since there are default fallback values, but having them I believe improves readability since
- this change should not change the outcome
=> chore(docker): add omitted arguments into compose file

docker/compose.yaml, docker/coreboot/Dockerfile, docker/edk2/Dockerfile, docker/linux/Dockerfile, tests/test_linux.sh
Preparing for multi-arch support, `arm64` specifically.
I did test the functionality manually on `arm64` machine, so I guess it is fine for now. I definitely still works for `x86` (`amd64`) since the tests are passing.
If there is some issue with `arm64` builds, then I can fix them in PR which will actually use this feature.
=> feat: dockerfile support multi arch

.github/workflows/example.yml
This this the correct way to handle caching.
=> chore(ci): correction to example caching

docker/compose.yaml
Not critical but, but it bugs me :D (pun intended)
=> fix(docker): typo in compose.yaml

.github/workflows/cache-cleanup-branch.yml, .github/workflows/cache-cleanup-pull-request.yml
- as it was now, cache-cleanup-pull-request would delete all caches, which is not what we want
=> ci: fix cache cleanup

action.yml
- in action.yml the ARCH change is broken since 32583f79
- for more details see comment in the file
=> fix(examples): partial revert of 32583f79

.github/workflows/example.yml, docker/compose.yaml
@LeanSheng I hope this is correct
among other things also fixes #413
=> feat(docker)!: bump GCC_VERSION for edk2-202408.01

.gitignore, Taskfile.yml, tests/Taskfile.yml
Comes handy for development and debugging.
=> test(examples): add taskfile to run Linux example locally

action/recipes/linux.go
- instead of copy use move on the defconfig
=> fix(action): linux make defconfig file conflict

action/recipes/linux.go, action/recipes/recipes.go
```
$ ls -a1lh /workdir/arch/x86/boot/bzImage
lrwxrwxrwx 1 root root 22 Nov 19 17:06 /workdir/arch/x86/boot/bzImage -> ../../x86/boot/bzImage
```
=> fix(action): infinite symlink issue

CONTRIBUTING.md
I tried to migrate but seems like too much work
See #402
=> docs(contributing): update

docker/compose.yaml, docker/edk2/Dockerfile
=> fix(docker): udk2017 needs python2

.cspell.json, action/container/container.go
- this specific problem can be difficult to diagnose
- add check for missing kernel module
- into general error add link to dagger troubleshooting guide
=> chore(action): on dagger error check of kernel module

action/recipes/config.go
- add more information into the configuration overview table
=> docs(action): improve configuration overview

.github/workflows/go-test.yml, action/main.go, action/recipes/config.go, action/recipes/universal.go, action/recipes/universal_test.go, action/recipes/uroot.go, docs/src/firmware-action/config.md
fixes #244 
I just copied `u-root` and renamed stuff, removed unnecessary things, and changed the build command into slice instead of single string.
=> feat: add universal module

docker/compose.yaml, docker/coreboot/Dockerfile
=> chore(docker): bump coreboot docker containers from jammy to noble

.github/workflows/docker-build-and-test.yml
- improve the coreboot toolchains pull requests made into firmware-action-toolchains repo
- change PR title
- change PR body
- add labels
=> ci: cleanup coreboot toolchain PRs

docker/coreboot/Dockerfile, docker/edk2/Dockerfile, docker/linux/Dockerfile, docker/uroot/Dockerfile
=> chore(docker): remove ssh server from containers

.cspell.json, .dagger-ci/Taskfile.yml, .dagger-ci/daggerci/lib/env.py, .dagger-ci/daggerci/lib/orchestrator.py, .github/workflows/container-cleanup.yml, .github/workflows/docker-build-and-test.yml
Now we can publish to both GitHub and DockerHub
fixes #552
=> feat: publish to dockerhub

docker/coreboot/Dockerfile, docker/edk2/Dockerfile, docker/linux/Dockerfile, docker/uboot/Dockerfile, docker/uroot/Dockerfile
let's unify the containers on these 3 tools
fixes #547
=> chore(docker): add git wget and curl to all containers

cmd/firmware-action/recipes/linux_test.go
- we changed naming of Linux containers, but forgot to update the golang tests
=> fix(cmd): golang test for linux module

cmd/firmware-action/main.go, shell-completion/firmware-action.bash, shell-completion/firmware-action.fish, shell-completion/firmware-action.usage, shell-completion/firmware-action.zsh
Just add a CLI command to do a configuration file(s) validation and quit.
fixes #555
=> feat: config validation

README.md, docs/src/firmware-action/build_dockerfile_on_the_fly.md, docs/src/firmware-action/config.md, docs/src/firmware-action/get_started/04_get_firmware_action.md, docs/src/firmware-action/get_started/05_run_firmware_action.md, docs/src/firmware-action/get_started/06_run_in_ci.md, docs/src/firmware-action/offline_usage.md, docs/src/firmware-action/usage_local.md
Mostly just putting the "firmware-action" into back-ticks.
Updated `--help`
=> docs: cosmetic

action.yml
=> fix(action): upload artifact only for specified target

.github/workflows/documentation-pages.yml
- the cache seems to be growing over time, so I hope this will stop it
- also some minor improvements
=> chore: mdbook

.cspell.json, cmd/firmware-action/container/container.go, cmd/firmware-action/container/container_test.go
- containers are now in both GitHub and DockerHub registries
- add unit-test to validate functionality
=> fix(cmd): update detection of discontinued containers

Taskfile.yml, cmd/firmware-action/.goreleaser.yaml, cmd/firmware-action/Taskfile.yml, cmd/firmware-action/kernel-modules-load.conf
I hope this works. I made a `Taskfile` to locally test things.
- making some goreleaser defaults explicit
- add nFPM to goreleaser
- add config to automatically load linux kernel modules
- add Taskfile
fixes #653
=> feat: goreleaser tweaks

.github/workflows/example.yml, action.yml, cmd/firmware-action/recipes/recipes.go, tests/example_config.json, tests/example_config__universal__with_nested_output.json
=> fix: packing unpacking

.github/workflows/go-test.yml, README.md
Adding a job to merge the coverage reports. Not sure what to do about it afterwards.
=> ci: docs and tests

.github/workflows/example.yml, cmd/firmware-action/recipes/uboot_test.go
This reverts commit 836c4ebe57124f7873ab58c0fc426335b83fdafc.
=> ci(fix): upstream u-boot repo accessible again

.github/workflows/example.yml
- uroot was failing to compile because of bug in tokeninternal
- https://github.com/golang/go/issues/74462
=> fix: uroot compilation issues
