.checkov.yml
Silence CKV_DOCKER_3: "Ensure that a user for the container has been created". We don't want to use a non-root user do to use of volumes in local builds.
=> fix: Add .checkov.yml

.github/workflows/docker-build-and-test.yml
Publish only on release or on main branch. This should keep the container registry clean.
=> ci: make publishing conditional

.github/workflows/docker-build-and-test.yml, .github/workflows/lint.yml, .github/workflows/pytest.yml
- push to branch with existing pull request should no longer create duplicate workflows / actions for push and pull
=> ci: tweak triggers for ci

docker/coreboot/Dockerfile
- just a cosmetic thing to unify tags across repo
=> chore(coreboot): change ubuntu release from 22.04 to jammy

.github/workflows/docker-build-and-test.yml, .github/workflows/lint.yml, .github/workflows/pytest.yml
The current workflows do not run when stuff gets merged into `main`. This should hopefully fix it.
=> ci: run ci also when PR is merged to main

action/recipes/coreboot.go
- for blobs the build scrips or makefile tries to make them into absolute path by pre-pending current working directory (so far observed only for FSP, but that might be because FSP was the first blob to be included)
- simple solution is to use just relative paths inside the container
... it is always the path ...
=> fix(action): use relative paths for blobs in container

action/recipes/config.go, action/recipes/coreboot.go, action/recipes/coreboot_test.go, action/recipes/edk2.go, action/recipes/edk2_test.go, action/recipes/linux.go, action/recipes/linux_test.go, action/recipes/recipes.go, tests/example_config.json
Cleanup code by using interfaces and add options for outputs.
I tired not to go all out with use of interfaces, but I think this is reasonable and significantly cleans up the code. I really like that now there are no `if coreboot ... else if linux ...`. Should much more scalable now.
fixes #100 
In essence, until now the files / directories that were extracted out of container after successful build were hard-coded. Now user can configure them! This greatly increases the flexibility.
This was also needed to get Intel FSP fully working. Previous PR #95 allows to build Intel FSP, but to actually get compiled stuff out, this feature is needed.
=> refactor build system

docker/coreboot/Dockerfile
`ifdtool` and `cbfstool` are compiled in `toolchain` stage, but are not copied over to `final` stage.
=> fix(docker): missing ifdtool and cbfstool in container

.github/workflows/example.yml
I can see that sometimes the `git clone` fails on coreboot stuff. I assume this is because today this project has been just hammering down a lot of things thanks to the new dependencybot :D
Anyway, this should reduce the load. There is minor speed increase too, but minuscule.
=> ci: add cache to reduce stress on git hosting servers

.github/workflows/docker-build-and-test.yml
- remove 'merge_group' since you cannot specify change paths, also we do not have any of the jobs as required anymore because of the time it takes to complete; furthermore 'pull_request' jobs should be enough to prove viability of changes
- trigger on 'push to main' only if changes in docker files, so that pull requests do not trigger so many jobs
- add weekly build (Sunday midnight)
Related to #128, also tackles #135 by reducing number of published containers.
=> ci(action): further reduce load on CI

.github/workflows/example.yml
Will keep failing until a new container for this coreboot is published (wait until #154 is merged).
=> add coreboot 24.02 example

.github/workflows/lint.yml
Somehow this little thing sneaked in and remained there for a long time.
=> ci(workflows): change go version in linting to stable

.github/workflows/docker-build-and-test.yml
- add a step in docker-build-and-test to delete old published containers
- should delete all but 'main', 'latest' and release containers
- we have to use my own fork of `actions/delete-package-versions` at the moment to have access to `dry-run` and `ignore-versions-include-tags` features
- [dry-run](https://github.com/actions/delete-package-versions/pull/119/commits)
- [tags](https://github.com/actions/delete-package-versions/pull/104)
Fixes #135
=> ci: delete old containers in packages

action/container/ssh.go, action/container/ssh_test.go, action/main.go, action/recipes/config.go, action/recipes/coreboot.go, action/recipes/coreboot_test.go, action/recipes/edk2.go, action/recipes/edk2_test.go, action/recipes/linux.go, action/recipes/linux_test.go, action/recipes/recipes.go, action/recipes/recipes_test.go, action/recipes/stitching.go, action/recipes/stitching_test.go
- on build failure open ssh server in the container and let user connect into it to debug the problem
- to enable this feature user has to pass argument `--interactive`
- into the containers add few editors (nano, vim), tools and utilities people would expect
- ssh login is with password, which is randomly generated
Fixes #109 
Testing will be pain, but I think there needs to be some. So I will take a look at it.
=> make containers interactive

action/container/container.go, action/recipes/coreboot.go, action/recipes/edk2.go, action/recipes/linux.go, action/recipes/recipes.go, action/recipes/stitching.go
- part 2: this one only replaces `log.Printf` with `slog` (maybe also removes `log.Fatal`)
- fixes #107 
- requires:
- #157
- #147
- #137
=> refactor logging pt2

docker/edk2/Dockerfile
- rustup default installation takes up 1.1 GB of space
- the minimal profile should reduce it to half or so
- https://rust-lang.github.io/rustup/concepts/profiles.html
In my defense, I had no idea it is so huge!
=> perf(docker): reduce rust size

action/container/ssh.go
We only use the scan function as blocker to for user input. Content of said input is irrelevant. Hence we should be able to ignore any error I believe.
=> fix: return not checked in container/ssh.go

.github/dependabot.yml
For one I think we can increase the limit since it has been running for a while now.
I added this when enabling `dependabot` for this repository to limit the number of pull requests, since each PR creates a bunch of workflows. And I suspected that it would create a bunch of PRs in the beginning. Now it is no longer needed.
So lets keep it to default, which is `5`.
=> ci(dependabot): increase open-pull-requests-limit to default

package-lock.json
Manually update `npm` packages. We have a blocking issue with security patches for `tar` and `braces` packages, and for whatever reason `dependabot` did not update them yet.
=> build(deps): run update on npm packages

.github/workflows/docker-build-and-test.yml, .github/workflows/release-prepare.yml, .github/workflows/release.yml
OK, this is a bit cumbersome, but it should fix the problem then a new release does not trigger a build of Docker containers.
=> Run docker container builds on release

.markdown-link-check.json
The link test of AUR fails very often, so let's ignore it.
=> fix(lint): fix frequent markdown-link-check fail with AUR link

.github/workflows/example.yml, .github/workflows/go-test.yml, .github/workflows/lint.yml, .github/workflows/pytest.yml
- it is just doubling number of CIs of each PR
- we have this only because the release PR does not trigger corectly workflows, because we have too many nested triggers I think (github has a limit to prevent infinite loops)
- this fix should shopefully skip PR review trigger when the PR is not made by the github-actions[bot] which we use for releases
=> fix(ci): skip on all reviews except when the release PR

.github/workflows/release-prepare.yml
- workflow release-prepare does not get current version, and defaults to current version being v0.0.0
- for workflow release-prepare to correctly get current we need the whole history and all tags
=> fix(release): release-prepare missing tags and history

.github/workflows/release-prepare.yml, action.yml
We are getting some failures when the action is trying to download the executable from releases.
Right now it just downloads a small text file with `Not found` written inside it. This is because of the apostrophes surrounding the `firmware-actin` version in the URL.
=> fix(action): remove unnecessary apostrophes

.github/workflows/example.yml, .github/workflows/lint.yml
- we are using pull_request_review.submitted trigger to have CIs running for release PRs and releases
- the issue is that when someone submits a review on ordinary PR, it creates a bunch of jobs which are immediately skipped, but they still cancel already running jobs because they are in the same group
=> fix(ci): jobs are canceled on submitted review

.github/workflows/example.yml, .github/workflows/go-test.yml, .github/workflows/pytest.yml
- some jobs take a while so we skip them if unnecessary
- they show up as SKIPPED
- problem is that SKIPPED is considered FAILED and we cannot have these as required status checks
- this allows us to change this behavior
=> fix(ci): consolidate multiple jobs into few status checks

.cspell.json, .github/workflows/docker-build-and-test.yml
Sometimes the docker-compose executable is missing for some reason.
See failing [v0.5.0 release dagger workflow](https://github.com/9elements/firmware-action/actions/runs/10195463439)
=> fix(dagger): missing docker-compose

docker/coreboot/Dockerfile
- if I am not mistaken we selected only few platforms to to save on compile time when building the docker containers
- since we are no longer building docker containers for each and every commit and/or pull request, I think we can support all platforms
- instead of 40 minutes per container it takes 60 minutes
=> feat(docker): build coreboot cross-compilers for all platforms

.github/workflows/bot--reminder-schedule.yml
I noticed that the reminderbot does not work yet on #302 , and then I found out I missed a important detail.
In the first PR #303 I forgot that the reminder bot consists of two separate parts, but it should have become apparent with #328.
Anyway:
- 1st part creates the label and metadata on issue creation
- 2nd part runs on schedule and checks labeled issues
=> feat(ci): add 2nd part to reminder bot

.dagger-ci/daggerci/lib/orchestrator.py, .github/workflows/docker-build-and-test.yml
This time the tests are done without tarball export and import which should save up a lot of disk space and a bit of CI time.
fixes #338
=> fix(docker): enable again tests of containers

docker/linux/Dockerfile
I just noticed that the Linux docker container is missing `zstd`, lol
=> feat(docker): add zstd into linux container

.github/workflows/docker-build-and-test.yml
- I don't think we need to re-build the containers this often
=> ci(docker): build monthly instead of weekly

.cspell.json, .github/workflows/docker-build-and-test.yml
- instead of hard-coded matrix of docker containers, generate it automatically
- I also include matrix subsets only with `coreboot` and `edk2` entries, they will be needed later
=> ci(docker): dynamically generate the matrix

docker/compose.yaml
First of all, I don't think this will have any effect on the containers or their usage.
During building of the `multi-arch` containers there were multiple issues:
- missing `gpg2` executable for arm64
- missing `gcc-11-aarch64-linux-gnu` package
- became available only since ubuntu noble (24.04) for arm64
I just don't see any benefit of trying to keep using ubuntu jammy (22.04) since Linux kernel should compile almost anywhere.
=> fix(docker): bump all linux docker containers to noble release

.github/workflows/bot--reminder-schedule.yml
For those few reminders that we have there is no need to have hourly resolution. Daily is more than sufficient.
=> ci(reminder): run daily instead of hourly

docker/coreboot/Dockerfile
This is still a leftover from original Dockerfile from February 2023 2dbdbb581e6e99446a7896a5698e3aa23a286e8a. I don't think we actually need this.
=> chore(docker): remove unnecessary dependencies

.cspell.json, .github/workflows/cache-cleanup-branch.yml, .github/workflows/cache-cleanup-pull-request.yml, .github/workflows/example.yml
- we are running out of cache space and the default GitHub eviction policy is not ideal
- these jobs should make the caching more optimal for our use-case
=> ci: workflows to clear cache in smarter way

.github/dependabot.yml
Let's use dependabot to keep our git submodules up-to-date.
=> ci: dependabot git submodules

action/recipes/edk2.go
This code was left in there because I though it might become useful alter on, but it does not seems to be the case (the need did not arise since). So let's remove this.
=> chore(action): remove obsolete code

.cspell.json, .dagger-ci/daggerci/lib/orchestrator.py, .dagger-ci/daggerci/tests/test_orchestrator.py, .github/workflows/docker-build-and-test.yml, .gitignore, action/recipes/edk2.go, docker/coreboot/Dockerfile, docker/edk2/Dockerfile, docker/linux/Dockerfile
This makes all of our containers [multi-architectural / multi-platform](https://docs.docker.com/build/building/multi-platform/) and fixes #341 .
At the moment we only support `x86_64` (aka `amd64`) and `arm64` (specifically `arm64 v8`).
Todo:
- this is kinda difficult to test at the moment
There is a lot to comprehend, so here are some notes as to why:
- `u-root` and `linux` are OK to build the "normal way", however with `edk2` and `coreboot` I get errors when trying to compile to tool-chains - I suspect the problem to be native emulation not supporting all of the instructions required
- building `x86` on `x86` machine and `arm64` on `arm64` works fine, but building `arm64` on `x86` machine is broken (and vice versa)
- this means that I cannot build `edk2` or `coreboot` multi-arch …
=> feat(docker): make containers multi-arch

.dagger-ci/Taskfile.yml, Taskfile.yml
I am adding a new task into the `Taskfile.yml` inside `.dagger-ci` directory, which simplifies building single docker containers (mostly for development purposes).
I am also linking the the two taskfiles (the main one and one in the `.dagger-ci` directory) for simplicity.
Building coreboot containers will be a bit problematic after the #343 is merged because it will require to have pre-compiled tool-chain ready on disk :(
=> expand taskfile

.github/workflows/bot--automerge.yml
- automatically enable auto-merge on all pull requests
- if pull request is made by dependabot, also automatically approve it
- the dependabot pull request will still have to pass required checks in order to be merged
Inspired by [peter-evans/enable-pull-request-automerge](https://github.com/marketplace/actions/enable-pull-request-automerge)
=> ci: a bit more automation to pull requests

.github/workflows/example.yml, action.yml, action/recipes/linux.go, action/recipes/linux_test.go, action/recipes/recipes.go, tests/example_config.json, tests/example_config__linux.json
- add example test for `coreboot` on `arm64`
- add example test for `uroot` on `arm64`
- add example test for `linux` on `arm64`
- add example test for `stitching` on `arm64`
edk2 will come in later PR
=> test(examples): expand to also run on arm64 machine

.github/workflows/cache-cleanup-pull-request.yml
- it is just a cleanup job, no need to fail if the cache does not exist
=> fix(ci/cleanup): do not fail when cache not found

.github/workflows/bot--automerge.yml
These jobs fail when PR is just a draft
`pull_request` types by default include:
- opened
- synchronize
- reopened
So I added `ready_for_review`. This way, when the PR is converted from `Draft` to `Ready for review` it will also trigger the jobs.
=> ci(automerge): do not run on draft PR

.cspell.json, .github/workflows/bot--automerge.yml
My theory as to why GitHub does not trigger check jobs when Auto-merge is enabled by our bot is that GitHub does not allow ordinary `GITHUB_TOKEN` to trigger other workflows. Probably to avoid endless recursion.
We had this problem also with releases. So I hope that using PAT might fix this.
=> fix(ci/automerge): use PAT token

.github/dependabot.yml
- we never use it anyway
- when I added it I was young and foolish, did not read the documentation properly
- all it would do is to add some metadata, and now I do not see any benefits
[Docs](https://docs.github.com/en/code-security/dependabot/ecosystems-supported-by-dependabot/supported-ecosystems-and-repositories#docker)
=> chore(dependabot): remove docker

.github/workflows/release-prepare.yml
- as it was until now, the 'sed' replaces all occurances of SEMVER
- this way, only the first global SEMVER will be replaced
=> fix(ci): replace only first semver in Taskfile

README.md
- add list of containers and their maintenance status
- I really want to inform people that some containers are no longer maintained, but I do not want to delete them yo no break other peoples stuff
=> docs: add notes on containers

.github/workflows/example.yml, .github/workflows/release-prepare.yml
- by default ietf-tools/semver-action errors when none of the commits results in a version bump
- configure the action to bump patch instead
=> fix(ci): next version calculation

action/recipes/config.go, action/recipes/config_test.go
- until now it was rather hard to debug when the issue was one or more missing environment variables
- with this patch, all environment detected variables in the JSON configuration file must be defined at the time of execution (can be empty)
Golang's [os.ExpandEnv](https://pkg.go.dev/os#ExpandEnv) does not perform such check:
> References to undefined variables are replaced by the empty string
fixes #384
=> feat(action): check for any undefined environment variable in config

.github/workflows/documentation-pages.yml
- currently the mdbook pages are missing things from the git submodules because they are not checked out
=> fix(docs): fix missing content from submodules

.cspell.json, action/filesystem/filesystem.go, action/filesystem/filesystem_test.go, action/go.mod, action/go.sum, action/main.go, action/recipes/config.go, action/recipes/recipes.go, action/recipes/recipes_test.go
- few fixes (mostly small stuff)
- speed up filesystem.DirTree (I just happened to stumble upon it)
- add functions to detect changes in files
- add new filesystem functions which can detect changes in files base on time-stamps
- since we work with large projects, such as Linux Kernel, this detection should be as fast as possible
- to make it fast, we solely rely on time, no hashing
- the idea is that firmware-action will create a time-stamp file at the end of each execution (for each target)
- at the start of each execution firmware-action will load time-stamp file from previous execution and check if any file in sources is newer that the saved time-stamp
- the detection function is lazy, and will return on first positive match
- if the no file in sources is newer, target should be …
=> feat: detect changes in sources

.github/dependabot.yml
- we had some issues with goilang updates when one faulty package would block updating another
=> chore(dependabot): split updates for golang

action/go.mod, action/go.sum
This should silence the linters and dependabot
=> chore(deps): bump x/net due to an upstream CVE

action/recipes/coreboot.go
- with this patch, changes to any blob will also trigger a rebuild
=> feat(action): add coreboot blobs into GetSources

docs/src/firmware-action/get_started/04_get_firmware_action.md, docs/src/firmware-action/usage_local.md
Forgot to update docs for #447
=> docs: update firmware-action installation instruction

docker/edk2/Dockerfile
- some edk2 containers have NodeJS v16 or older, which are end-of-life
- so let's add NodeJS repository for NodeJS v20 LTS
- we could also do v18 LTS, but it is going to be end-of-life soon
- only edk2 is finicky, other containers should rather upgrade the use Ubuntu version if this problem arises
fixes #494
=> fix(docker): install newer NodeJS into edk2 containers

README.md
- consistently use form "firmware-action" across README.md
- also note a support for universal module
=> docs: unify firmare-action name in README

.cspell.json, .gitignore, cmd/firmware-action/environment/environment.go, cmd/firmware-action/environment/environment_test.go, cmd/firmware-action/filesystem/git.go, cmd/firmware-action/filesystem/git_test.go, cmd/firmware-action/recipes/coreboot.go
The motivations behind this:
- coreboot likes to embed its source version into the compiled binary
- coreboot does that by calling `git describe ...`
- however with firmware-action we can assume people will include coreboot as git submodule, and thus when compiling coreboot in container the git commands will fail because of missing `.git` directory
- to fix this we will run manually the `git describe` command and then pass it in form of env variable into the container
The coreboot part `crebootPassEnvVars` is not tested now. I am too tired to look into unit-testing that right now (the supporting functions have unit tests).
I just ran the `firmware-action` on one project and tested it manually - it seems to work exactly as expected. Not sure if it is worth it to write unit-test.
@MDr164 if …
=> feat: coreboot git describe

docker/compose.yaml, docker/edk2/Dockerfile
- NodeJS v20 requires libc6 version >= 2.28, but that is not possible with this old Ubuntu
- switching to newer Ubuntu is not a option either because of how fragile and snowflaky edk2 is
- updating libc6 is just a terrible idea, that means that udk2017 cannot run NodeJS v20
- ~~the best we can do is to run v18, which is end-of-life soon, but that is the best we can do~~
- **UPDATE: the best we can do v16, everything else is too new for this old Ubuntu**
- still, it is much better than v10 that the Ubuntu Bionic (18.04) ships with
fixes #500
=> fix(docker): downgrade NodeJS for udk2017

cmd/firmware-action/filesystem/filesystem_test.go, cmd/firmware-action/filesystem/git_test.go, cmd/firmware-action/recipes/linux_test.go, cmd/firmware-action/recipes/recipes_test.go
- fix order of parameters to match expected and actual
fixes #502
=> chore(cmd): unify assert parameters

cmd/firmware-action/filesystem/git.go, cmd/firmware-action/recipes/coreboot.go, cmd/firmware-action/recipes/coreboot_test.go, cmd/firmware-action/recipes/edk2_test.go, cmd/firmware-action/recipes/linux_test.go, cmd/firmware-action/recipes/stitching_test.go
=> test: coreboot version passing

.github/workflows/example.yml
- while these fail normally, right now they are failing because of undefined environment variables
- this is easy to fix problem
=> fix(ci): example runs on windows and macos

cmd/firmware-action/environment/environment_test.go, cmd/firmware-action/recipes/config_test.go, cmd/firmware-action/recipes/coreboot_test.go, cmd/firmware-action/recipes/stitching_test.go
- replace log.Print() and fmt.Print() with t.Log()
fixes #247
=> chore(cmd): fixup logging in tests

.github/workflows/container-cleanup.yml, .github/workflows/docker-build-and-test.yml
- currently have a issue with Docker being unable to pull some containers
- maybe there is a bug in this step for removing old contianers causing problems, we could try to temporarily remove it
=> ci(docker): stop removing old containers

.dagger-ci/daggerci/lib/git.py, .dagger-ci/daggerci/tests/test_git.py
- we are still having some issues with Docker pulling containers, maybe increasing the short git commit sha form default 8 characters to 12 will improve things (it will certainly decrease the likelihood of collision)
=> ci(docker): increase git commit sha slug to 12 characters

cmd/firmware-action/container/container.go, cmd/firmware-action/container/container_test.go, cmd/firmware-action/recipes/config.go, cmd/firmware-action/recipes/coreboot.go, cmd/firmware-action/recipes/coreboot_test.go, cmd/firmware-action/recipes/edk2.go, cmd/firmware-action/recipes/edk2_test.go, cmd/firmware-action/recipes/linux.go, cmd/firmware-action/recipes/linux_test.go, cmd/firmware-action/recipes/recipes.go, cmd/firmware-action/recipes/stitching.go, cmd/firmware-action/recipes/stitching_test.go, cmd/firmware-action/recipes/universal.go, cmd/firmware-action/recipes/universal_test.go, cmd/firmware-action/recipes/uroot.go, cmd/firmware-action/recipes/uroot_test.go, docs/src/SUMMARY.md, docs/src/firmware-action/build_dockerfile_on_the_fly.md, docs/src/firmware-action/features.md
- for a while now there was a functionality to build Docker containers on the fly from Dockerfile, but this feature was not exposed to the user
- this patch exposes the feature
- it will not work will with our Dockerfiles out of the box because they are meant to be used with accompanying Docker Compose file, so using one of our Dockerfiles would require to edit it (just replace default ARG values with desired ones)
fixes #163
=> feat(cmd): expose building contianers on the fly

cmd/firmware-action/container/container.go, docs/src/docker/docker-compose.md
- print a simple warning when people use discontinued containers
- the regex list should remain in sync with list in README.md
fixes #554
=> feat(cmd): warning about using discontinued containers

.github/workflows/docker-build-and-test.yml, .github/workflows/example.yml
- we are getting 443 from review.coreboot.org when multiple builds run in short succession
- these changes should improve caching and reduce load we put on coreboot infrastructure
I changed caches in examples so that we do not get conflicts. Technically speaking the content could be re-used but `actions/cache` are finecky. Not only that they have to match the `key`, but also the `paths`, and in `example.yml` we have named the coreboot repositories `./my_super_dooper_awesome_coreboot`, while in `docker-build-and-test.yml` we call it just `coreboot`.
=> ci: better caching for coreboot

cmd/firmware-action/recipes/coreboot.go
- thanks to our JSON configuration supporting environment variables, it is possible that users will end up if configuration where blob key-value pair has empty value or key
- simply ignore pairs where either key or value is empty string
=> fix(cmd): empty coreboot blob handling

.github/workflows/example.yml
Should no longer fail when executed on release.
=> fix(example): fail on release

cmd/firmware-action/recipes/linux_test.go
=> chore: cosmetic

.github/workflows/example.yml, cmd/firmware-action/main.go, cmd/firmware-action/recipes/config.go, cmd/firmware-action/recipes/config_test.go, docs/src/firmware-action/config.md
=> feat: support multiple configs

.github/workflows/lint.yml, .github/workflows/release-prepare.yml, Taskfile.yml, cmd/firmware-action/.gitignore, cmd/firmware-action/.goreleaser.yaml, cmd/firmware-action/main.go, tests/Taskfile.yml
- update to v2
- NOTE: some options we were still using there were deprecated
- goreleaser already passes version based on git describe as `ldflag` along with commit and date (source: https://goreleaser.com/cookbooks/using-main.version/)
- the main Taskfile now replicates the same exact behavior as goreleaser
- we no longer have to keep these hardcoded strings in sync
- when people build from source the version string is much more descriptive
=> feat: add goreleaser linting check and replace hardcoded version strings

.github/workflows/container-cleanup.yml, docs/src/docker/docker-compose.md
I have not seen or heard any problems related #549, so I think we turn the cleanup on again, but this time as separate workflow (see #536).
- run weekly
- also keep discontinued containers clean
Discontinued containers did get rather messy, for `linux_6.1.45` we had over 30 un-tagged images (not anymore since I ran this manually).
I do see warnings on `coreboot_4.20` and `coreboot_4.22`, but that is because there is no such package / container anymore (I suspect that we switched to `coreboot_4.20.1` and `coreboot_4.22.01` faster than we make releases, and maybe overzealous cleanup removed them? Not sure. But it is only warning on discontinued container, so I don't really care.
=> fix: container cleanup

.github/workflows/example.yml, action.yml, cmd/firmware-action/container/container.go, cmd/firmware-action/environment/environment.go, cmd/firmware-action/main.go, cmd/firmware-action/recipes/recipes.go, cmd/firmware-action/recipes/recipes_test.go, tests/example_config.json, tests/example_config__depends.json
Delete a container in GitHub CI to conserve disk space.
As mentioned in one of the comments, it is not really possible to delete only the specific container. They are somehow embedded into the Dagger Engine (don't know how, possibly in the attached docker volume). So as a workaround we remove the whole Dagger Engine container and it's volume (but keep Dagger Engine image, to not download it again).
This way keep reclaiming disk space, and surprisingly there is not much time-penalty.
Given how it works under the hood, I thought it would be better to avoid automatic enforcement if GitHub CI is detected, and instead as enable this behavior with optional argument.
fixes #560
=> feat: delete container after use

.github/workflows/container-cleanup.yml
- seems like this is what breaks the docker pull
- I have just seen a CI fail when trying to pull `v0.12.0` docker container from GitHub
related to issue #549
=> ci: disable scheduled container-cleanup

action.yml
- the artifact name for automatic upload is derived (among other) from 'output_dir', which can contain forward slashes
fixes #629
=> fix(action): remove forward slashes from artifact name

.github/workflows/docker-build-and-test.yml
- the test directory now contains much more files than it did back when the path filter in 'docker-build-and-test.yml' was written
- now it contains even un-related files
- we only need the to concern ourselves with the shell script, as they are self-contained, and some defconfig files
=> ci: optimize when docker containers are build

.github/workflows/example.yml
- fix undefined environment variable
- also reduces number of example test to almost half
As for the `test-operating-systems` tests:
- we don't really have any use-case for this anyway
- also, these tests always fail anyway
- we might need it in the future, which is why I am keeping the whole body of the test
=> fix: tests

.github/workflows/go-test.yml, cmd/firmware-action/recipes/coreboot_test.go
Cache temporary files at `/tmp/__firmware-action_tmp_files__` for `go-test` CI.
Should speed up the CI run.
=> ci: speed up go-test

.github/workflows/release-prepare.yml, action.yml, cmd/firmware-action/recipes/recipes.go
You can see how this works in [throwaway firmware-action-example PR 30](https://github.com/9elements/firmware-action-example/pull/30), specifically in the `separate jobs` workflow. The mentioned PR should be discard after this one is merged.
So here are few small fixes:
- forgot to pass `debug` from `action.yml` input to `firmware-action` executable
- make compile option work in other CIs (until now this option was only usable in this specific repository, but from now on users can compile and use some cutting edge feature too!)
- for that to work we needed to add optional input for version (specifies tag or branch)
- fixed handling of artifacts (cache and artifact upload)
- small CI optimizations and fixes
=> fix(ci): auto upload

cmd/firmware-action/container/container_test.go, cmd/firmware-action/filesystem/git_test.go, cmd/firmware-action/go.mod, cmd/firmware-action/recipes/coreboot_test.go, cmd/firmware-action/recipes/edk2_test.go, cmd/firmware-action/recipes/linux_test.go, cmd/firmware-action/recipes/recipes_test.go, cmd/firmware-action/recipes/stitching_test.go, cmd/firmware-action/recipes/uboot_test.go, cmd/firmware-action/recipes/universal_test.go, cmd/firmware-action/recipes/uroot_test.go
- T.Chdir was introduced in new golang v1.24
- it makes test much cleaner
fixes #612
=> refactor(cmd): use T.Chdir for cleaner tests

docker/compose.yaml, docker/uroot/Dockerfile
- u-root recently bumped golang version to v1.24
- we are now doing the same
- this should not have any negative effects
- golang should be fully backwards compatible
fixes #666
=> chore(docker): bump golang to v1.24 for u-root

.github/workflows/example.yml
- when making a PR for the next release, the merge group checks fail in the example workflow
- they fail because the CURL cannot download the binaries for yet not-existing release
- updating the paths-filter should fix this because when new release is about to happen the action.yml file is always changed because it contains hard-coded version string
=> fix(ci): release merge group checks
